# Generated by Django 4.2.3 on 2023-07-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page', '0003_updateusername_updateemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateusername',
            name='user',
        ),
        migrations.DeleteModel(
            name='UpdateEmail',
        ),
        migrations.DeleteModel(
            name='UpdateUsername',
        ),
    ]
